name: Build Windows

on: [pull_request, push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Setup CMake
      run: cmake . -DCMAKE_BUILD_TYPE=Release
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release cbsodata_dumper.sln
