name: Build Windows

on: [pull_request, push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Setup CMake
    - run: cd cbsodata_dumper && cmake . -B build -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
    - run: cd build && cmake --build . --config Release
